# Generated by Django 4.2 on 2023-04-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateField(default="1999-10-18"),
            preserve_default=False,
        ),
    ]
